#!/usr/bin/env bash
# PreToolUse hook: blocks Edit/Write on managed governance files.
# Distributed by docs-control via managed_files sync.
# Exit 0 = allow, Exit 2 = block (stderr shown to Claude).
set -euo pipefail

# ── Guard: exit if no stdin data (e.g., linter running script) ───────
# read -t 0 checks if stdin has data without consuming it.
# BASH_EXEC and other linters run scripts without piped input.
if ! read -t 0 2>/dev/null; then
  exit 0
fi

# ── Self-exclusion: allow edits in the governance source repo ───────
REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
SCRIPT_DIR_EARLY="$(cd "$(dirname "$0")" && pwd)"
GOVERNANCE_EARLY="${SCRIPT_DIR_EARLY}/../governance.json"
SOURCE_REPO=""
if [ -f "$GOVERNANCE_EARLY" ]; then
  SOURCE_REPO=$(jq -r '.source_repo // empty' "$GOVERNANCE_EARLY" 2>/dev/null || echo "")
fi
if [ -n "$SOURCE_REPO" ] && [ -n "$REMOTE_URL" ]; then
  REMOTE_PATH=$(echo "$REMOTE_URL" | sed 's|\.git$||' | sed -E 's|.*[:/]([^/]+/[^/]+)$|\1|')
  if [ "$REMOTE_PATH" = "$SOURCE_REPO" ]; then
    exit 0
  fi
fi

# ── Read tool input from stdin ──────────────────────────────────────
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || echo "")

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# ── Normalize: strip leading ./ and resolve to repo-relative path ───
FILE_PATH="${FILE_PATH#./}"
# If absolute, strip the repo root prefix
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
if [ -n "$REPO_ROOT" ] && [[ "$FILE_PATH" == "$REPO_ROOT"/* ]]; then
  FILE_PATH="${FILE_PATH#"$REPO_ROOT"/}"
fi

# ── Load governance manifest ────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GOVERNANCE_FILE="${SCRIPT_DIR}/../governance.json"

if [ ! -f "$GOVERNANCE_FILE" ]; then
  exit 0
fi

# ── Honor per-repo skip_files opt-out ───────────────────────────────
# The current repo name is parsed from the origin remote (same source used
# for self-exclusion above). If this repo has an entry in governance.json's
# skip_files map and the edited file is listed, allow the edit — the file
# is not ecosystem-managed for this repo.
REPO_NAME=$(basename -s .git "$REMOTE_URL" 2>/dev/null || echo "")
if [ -n "$REPO_NAME" ]; then
  SKIPPED=$(jq -r --arg fp "$FILE_PATH" --arg repo "$REPO_NAME" \
    '.skip_files[$repo][]? | select(. == $fp)' \
    "$GOVERNANCE_FILE" 2>/dev/null || echo "")
  if [ -n "$SKIPPED" ]; then
    exit 0
  fi
fi

# ── Check if file is protected ──────────────────────────────────────
PROTECTED=$(jq -r --arg fp "$FILE_PATH" \
  '.protected_files[] | select(. == $fp)' \
  "$GOVERNANCE_FILE" 2>/dev/null || echo "")

if [ -n "$PROTECTED" ]; then
  SOURCE_REPO=$(jq -r '.source_repo' "$GOVERNANCE_FILE")
  cat >&2 <<EOF
BLOCKED: "${FILE_PATH}" is a managed file controlled by ${SOURCE_REPO}.

Do not edit this file directly. To propose a change:
1. Create an issue at https://github.com/${SOURCE_REPO} describing the change.
2. Submit a PR to ${SOURCE_REPO} modifying the canonical source.
3. Once merged, the file will be synced to all downstream repos automatically.

See .claude/governance.json for the full list of protected files.
EOF
  exit 2
fi

exit 0
