---
extends: default
ignore: |
  vendor/
  node_modules/
  docs/specifications/
rules:
  line-length: disable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  truthy:
    allowed-values: ["true", "false", "on"]
  comments:
    min-spaces-from-content: 1
